-- MySQL Script generated by MySQL Workbench
-- Fri Apr  4 17:21:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libro_lista
-- -----------------------------------------------------
/********************************************************
* This script creates the database named libro_lista 
*********************************************************/

DROP DATABASE IF EXISTS libro_lista;
CREATE DATABASE libro_lista;
USE libro_lista;

-- -----------------------------------------------------
-- Table `author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `author` ;

CREATE TABLE IF NOT EXISTS `author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `main_genre` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book` ;

CREATE TABLE IF NOT EXISTS `book` (
  `isbn` CHAR(13) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `publication_date` DATE NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_book_author1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reader` ;

CREATE TABLE IF NOT EXISTS `reader` (
  `username` VARCHAR(255) NOT NULL,
  `pw_hash` CHAR(31) NOT NULL,
  `salt` CHAR(22) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review` ;

CREATE TABLE IF NOT EXISTS `review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT UNSIGNED NOT NULL,
  `comments` TEXT NULL,
  `book_isbn` CHAR(13) NOT NULL,
  `reviewer` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_book1_idx` (`book_isbn` ASC) VISIBLE,
  INDEX `fk_review_reader1_idx` (`reviewer` ASC) VISIBLE,
  CONSTRAINT `fk_review_book1`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_reader1`
    FOREIGN KEY (`reviewer`)
    REFERENCES `reader` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lista` ;

CREATE TABLE IF NOT EXISTS `lista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `created_by` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lista_reader1_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_lista_reader1`
    FOREIGN KEY (`created_by`)
    REFERENCES `reader` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista_followings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lista_followings` ;

CREATE TABLE IF NOT EXISTS `lista_followings` (
  `lista_id` INT NOT NULL,
  `reader_username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`lista_id`, `reader_username`),
  INDEX `fk_lista_has_reader_reader1_idx` (`reader_username` ASC) VISIBLE,
  INDEX `fk_lista_has_reader_lista1_idx` (`lista_id` ASC) VISIBLE,
  CONSTRAINT `fk_lista_has_reader_lista1`
    FOREIGN KEY (`lista_id`)
    REFERENCES `lista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_has_reader_reader1`
    FOREIGN KEY (`reader_username`)
    REFERENCES `reader` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lista_content` ;

CREATE TABLE IF NOT EXISTS `lista_content` (
  `lista_id` INT NOT NULL,
  `book_isbn` CHAR(13) NOT NULL,
  PRIMARY KEY (`lista_id`, `book_isbn`),
  INDEX `fk_lista_has_book_book1_idx` (`book_isbn` ASC) VISIBLE,
  INDEX `fk_lista_has_book_lista1_idx` (`lista_id` ASC) VISIBLE,
  CONSTRAINT `fk_lista_has_book_lista1`
    FOREIGN KEY (`lista_id`)
    REFERENCES `lista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_has_book_book1`
    FOREIGN KEY (`book_isbn`)
    REFERENCES `book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
